"""Declared vocabulary, stable identity, and the types the pipeline moves."""

from metric.ontology.ids import (
    canonical_name,
    document_id,
    entity_id,
    literal_id,
    passage_id,
    sha256_file,
)
from metric.ontology.schema import (
    Cardinality,
    LiteralType,
    Polarity,
    RelationSpec,
    Schema,
    SchemaError,
    load_schema,
)
from metric.ontology.types import (
    LITERAL_TYPE,
    Candidate,
    Document,
    Entity,
    Materiality,
    Method,
    Passage,
    PassageKind,
    Question,
    Rejection,
    Span,
    TailKind,
    Triple,
    TripleStatus,
)

__all__ = [
    "LITERAL_TYPE",
    "Candidate",
    "Cardinality",
    "Document",
    "Entity",
    "LiteralType",
    "Materiality",
    "Method",
    "Passage",
    "PassageKind",
    "Polarity",
    "Question",
    "Rejection",
    "RelationSpec",
    "Schema",
    "SchemaError",
    "Span",
    "TailKind",
    "Triple",
    "TripleStatus",
    "canonical_name",
    "document_id",
    "entity_id",
    "literal_id",
    "load_schema",
    "passage_id",
    "sha256_file",
]
